export const FETCH_ALL_SERVICES_START = 'FETCH_ALL_SERVICES_START';
export const FETCH_ALL_SERVICES_SUCCESS = 'FETCH_ALL_SERVICES_SUCCESS';
export const FETCH_ALL_SERVICES_FAIL = 'FETCH_ALL_SERVICES_FAIL';
